/* ============================================================
   All copy and product data lives here so the page components
   stay about layout. Swap prices / links here when they change.
   ============================================================ */

export const STORE_URL =
  "https://www.amazon.in/stores/Amblitz/page/F623C10F-C3BF-4001-89A2-E86E0322EF4F";

export const nav = [
  { label: "Range", href: "#range" },
  { label: "Bestsellers", href: "#bestsellers" },
  { label: "Naam Lekhan", href: "#naam" },
  { label: "Collection", href: "#collection" },
  { label: "Bulk orders", href: "#bulk" },
  { label: "FAQ", href: "#faq" },
];

export const categories = [
  {
    id: "omr",
    name: "OMR practice sheets",
    hindi: "ओएमआर शीट",
    line: "Specimen answer sheets in the same layout you get in the hall — 100, 150 and 180 MCQ formats.",
    specs: ["A4", "70 GSM", "Single-side print", "50 / 100 sheets"],
    tone: "leaf",
    href: "#bestsellers",
  },
  {
    id: "answer",
    name: "Answer-writing notebooks",
    hindi: "आंसर राइटिंग कॉपी",
    line: "Blank pages with pre-printed UPSC-style margins so you learn to answer inside the real word limit.",
    specs: ["A4", "200 / 300 pages", "Printed margins", "Spiral"],
    tone: "mango",
    href: "#bestsellers",
  },
  {
    id: "notebooks",
    name: "Ruled spiral notebooks",
    hindi: "रूल्ड नोटबुक",
    line: "Single-line 70 GSM paper that doesn't ghost, bound to lie flat on a crowded study table.",
    specs: ["A4", "200 pages", "Single line", "Lies flat"],
    tone: "ink",
    href: "#bestsellers",
  },
  {
    id: "naam",
    name: "Naam Lekhan pustika",
    hindi: "नाम लेखन पुस्तिका",
    line: "Broad 18 × 6 mm boxes in sections of 108, from 22,000 naam up to 1,51,000. No deity image on the cover.",
    specs: ["B5 · 185×240", "70 GSM", "108-box sections", "Eco disposal"],
    tone: "marigold",
    href: "#naam",
  },
];

export const bestsellers = [
  {
    name: "Spiral Ruled Notebook - 200 Pages - A4 Size",
    sub: "Classic Ruled Spiral with Aesthetic Design",
    specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Everyday notebook",
    image: "/product/spiral-notebook.jpg",
    href: "https://www.amazon.in/Amblitz-Spiral-Notebook-Ruled-Single/dp/B08D8JV82C/ref=ast_sto_dp_puis",
  },
  {
    name: "Spiral Ruled Notebook - 300 Pages - A4 Size",
    sub: "Spirals with 70 GSM Thick Paper No-Bleed",
    specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Best seller",
    image: "/product/300-pages-spiral.jpeg",
    href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07V3WL8WR/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
  },
  {
    name: "Spiral Ruled Notebook - 500 Pages - A4 Size",
    sub: "8 MM Standard Ruling with Date and Page Block",
    specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Popular design",
    image: "/product/500-pages.jpeg",
    href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07WZ4M1BB/ref=ast_sto_dp_puis",
  },
  {
    name: "UnRuled Spiral Notebook - 400 Pages",
    sub: "Best for Practical Subjects and for Competitive Exam",
    specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 1",],
    tag: "Unruled",
    image: "/product/unruled.jpg",
    href: "https://www.amazon.in/Amblitz-Spiral-Unruled-Notebook-Pages/dp/B07VY24KG6/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
  },
  {
    name: "UnRuled Spiral Notebook - 200 Pages - A4 Size",
    sub: "Unruled Pages No-Bleed Smooth Pages",
    specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Unruled",
    image: "/product/20-cm.jpg",
    href: "https://www.amazon.in/Amblitz-Unruled-Spiral-Notebook-Page/dp/B08D8JHVK7/ref=ast_sto_dp_puis",
  },
  {
    name: "UnRuled Spiral Notebook - 500 Pages - A4 Size",
    sub: "Unruled Pages No-Bleed Smooth Pages",
    specs: [ "500 pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Big notebook",
    image: "/product/unruled-500-pages.jpg",
    href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-500-Unruled/dp/B07WZ4P715/ref=ast_sto_dp_puis",
  },
  {
    name: "UnRuled Spiral Notebook - 300 Pages",
    sub: "Bundle Pack of Unruled Notebook",
    specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 4"],
    tag: "Unruled",
    image: "/product/4-pack.jpg",
    href: "https://www.amazon.in/Amblitz-Spiral-Unruled-Notebook-Page/dp/B07VY1J1WD/ref=ast_sto_dp_puis",
  },
  {
    name: "UnRuled Spiral Notebook - 1000 Pages",
    sub: "Mega Notebook for Rigorous Practice",
    specs: ["1000 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "Biggest notebook",
    image: "/product/mega-spiral.jpg",
    href: "https://www.amazon.in/Amblitz-1000-Pages-Spiral-Notebook/dp/B08FHY4CR9/ref=ast_sto_dp_puis",
  },
  {
    name: "Spiral Notebook - Ruled - Rainbow Series - 1000 Pages",
    sub: "Different color Paper used for 6 sections in this Mega Notebook like Rainbow in the SKY",
    specs: ["1000 Pages", "Rainbow Series", "70 GSM", "Thick Paper"],
    tag: "For multi-subject notes",
    image: "/product/notebook-omr.jpg",
    href: "https://www.amazon.in/Amblitz-Notebook-Subjects-Colour-Rainbow/dp/B08XLRYSLS/ref=ast_sto_dp_puis",
  },
  {
    name: "Naam Lekhan Pustika - 1,00,000 Naam - B5 Size",
    sub: "Comprehensive Ram Nam Lekhan Pustika with Broad Boxes",
    specs: ["1,00,000 Naam", "108 Boxes Section", "Pack of 1"],
    tag: "One lakh naam",
    image: "/product/nam-100000.jpg",
    href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Organised-Spiral/dp/B0CLVQVN1V/ref=ast_sto_dp_puis",
  },
  {
    name: "OMR Sheet for Practice - 100 MCQ - 100 Sheet",
    sub: "Helps in Ascertainng Time to Circle Buble",
    specs: ["100 MCQ", "70 GSM", "Thick Paper", "Loose Sheets"],
    tag: "For mock tests",
    image: "/product/100loose.jpg",
    href: "https://www.amazon.in/Amblitz-OMR-Sheet-MCQs-Sheets/dp/B09HXY2DQV/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
  },
  {
    name: "UPSC Mains Answer Writing Notebook - 200 Pages",
    sub: "For Endless QCAB practice in designated Pattern",
    specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
    tag: "For Mains",
    image: "/product/upsc-writing.jpg",
    href: "https://www.amazon.in/amblitz-Writing-Notebook-Pre-Printed-Practice/dp/B088X661QN/ref=ast_sto_dp_puis",
  },
  {
    name: "UPSC Mains Answer Writing Notebook - 200 Pages",
    sub: "Word Limit Adherence with limited Space for Answer",
    specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
    tag: "For Mains",
    image: "/product/upsc-mains.jpg",
    href: "https://www.amazon.in/amblitz-Notebooks-Pre-Printed-Practice-Notebook/dp/B07WZ31YBQ/ref=ast_sto_dp_puis",
  },
  {
    name: "Spiral Notebook - Speialized Format - 3 part Notebook",
    sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
    specs: ["200 Pages", "Specialized Format", "Pack of 1"],
    tag: "For notemaking",
    image: "/product/template.png",
    href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DPZWR9/ref=ast_sto_dp_puis",
  },
];

// Har category ke andar products baad mein add karne hain (same shape jaise bestsellers)
export const collections = [
  {
    id: "spiral-a4",
    label: "Spiral Notebook · A4",
    products: [
      {
        name: "Spiral Ruled Notebook - 200 Pages - A4 Size",
        sub: "Classic Ruled Spiral with Aesthetic Design",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Everyday notebook",
        image: "/product/spiral-notebook.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-Ruled-Single/dp/B08D8JV82C/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Ruled Notebook - 300 Pages - A4 Size",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Best seller",
        image: "/product/300-pages-spiral.jpeg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07V3WL8WR/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 400 Pages - A4 Size",
        sub: "32 Lines per Page for extra writing Space",
        specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Popular design",
        image: "/product/creativity.jpeg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07W184WDK/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 200 Pages - A4 Size",
        sub: "Spiral Specific Both side Margins",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Everyday notebook",
        image: "/product/moon.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-Single-Line/dp/B07W39YRPR/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 500 Pages - A4 Size",
        sub: "8 MM Standard Ruling with Date and Page Block",
        specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Popular design",
        image: "/product/500-pages.jpeg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07WZ4M1BB/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 300 Pages - A4 Size",
        sub: "Best for Notes Taking and Practice",
        specs: [ "300 pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Big notebook",
        image: "/product/always-right.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-300-Single/dp/B07VXXQW1G/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 400 Pages - A4 Size",
        sub: "Aesthetic Design with Quote",
        specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Popular design",
        image: "/product/moon.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07W39LTV7/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Ruled Notebook - 200 Pages - A4 Size",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["200 pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "Everyday notebook",
        image: "/product/always-right.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-200-Single/dp/B07W3D4XFK/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Ruled Notebook - 500 Pages - A4 Size",
        sub: "Best for Notes Taking and Practice",
        specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Popular design",
        image: "/product/notebook-omr.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07WZ4NHZL/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Ruled Notebook - 300 Pages - A4 Size",
        sub: "Classic Ruled Spiral with Aesthetic Design ",
        specs: ["300 pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "Big notebook",
        image: "/product/notebook-omr.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-300-Single/dp/B07VZ17L4T/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Ruled Notebook - 600 Pages - Mega Series",
        sub: "Best for Notes Taking and Practice",
        specs: ["600 pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Mega Series",
        image: "/product/everyday.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-Single-28-5cm/dp/B07WPM7H2X/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Ruled Notebook - 1000 Pages - Mega Series",
        sub: "Mega Notebook for Rigorous Practice ",
        specs: ["1000 pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Mega Series",
        image: "/product/sunrise.jpg",
        href: "https://www.amazon.in/Amblitz-Pages-Spiral-Notebook-Single/dp/B09MW9764V/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "unruled-a4",
    label: "Unruled Spiral · A4",
    products: [
      {
        name: "UnRuled Spiral Notebook - 200 Pages - A4 Size",
        sub: "Unruled Pages No-Bleed Smooth Pages",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Unruled",
        image: "/product/500-pages.jpeg",
        href: "https://www.amazon.in/Amblitz-Unruled-Spiral-Notebook-Page/dp/B08D8JHVK7/ref=ast_sto_dp_puis",
      },
      {
        name: "UnRuled Spiral Notebook - 300 Pages - A4 Size",
        sub: "Best for Notes Taking and Practice",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Big notebook",
        image: "/product/5-subjects.jpg",
        href: "https://www.amazon.in/Amblitz-Unruled-Spiral-Notebook-A4-300/dp/B07VWZZMK2/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Premium UnRuled Spiral Notebook - 140 Pages",
        sub: "Notebook for Journaling, Sketching, Calligraphy, Notes-Taking",
        specs: ["140 Pages", "100 GSM", "Thick Paper", "Pack of 1"],
        tag: "Premium pick",
        image: "/product/fear.jpg",
        href: "https://www.amazon.in/amblitz-Unruled-Spiral-Notebook-Premium/dp/B0BTMFH6XK/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 400 Pages",
        sub: "Best for Practical Subjects and for Competitive Exam",
        specs: ["400 Pages", "100 GSM", "Thick Paper", "Pack of 1"],
        tag: "Unruled",
        image: "/product/unruled.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Unruled-Notebook-Pages/dp/B07VY24KG6/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 200 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Everyday notebook",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-200-Unruled/dp/B07W17L42M/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 500 Pages",
        sub: "Aesthetic Design with Quote",
        specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Big notebook",
        image: "/product/unruled-500-pages.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-500-Unruled/dp/B07WZ4P715/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 600 Pages",
        sub: "Best for Notes Taking and Practice",
        specs: ["600 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Biggest notebook",
        image: "/product/dream.jpg",
        href: "https://www.amazon.in/Amblitz-Mega-Spiral-Notebook-Unruled/dp/B08C5M7HGW/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 300 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Big notebook",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-300-Unruled/dp/B07W18CKFB/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UnRuled Spiral Notebook - 200 Pages",
        sub: "Aesthetic Design with Quote",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "Unruled",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/Amblitz-Ambi-Spiral-Unruled-Notebook/dp/B07W18NTGC/ref=ast_sto_dp_puis",
      },
      {
        name: "UnRuled Spiral Notebook - 500 Pages",
        sub: "Unruled Pages No-Bleed Smooth Pages",
        specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "Popular design",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-Beautiful-Motivational-Notemaking/dp/B07WZ29QPC/ref=ast_sto_dp_puis",
      },
      {
        name: "UnRuled Spiral Notebook - 1000 Pages",
        sub: "Mega Notebook for Rigorous Practice ",
        specs: ["1000 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "Biggest notebook",
        image: "/product/5-subjects.jpg",
        href: "https://www.amazon.in/Amblitz-1000-Pages-Spiral-Notebook/dp/B08FHY4CR9/ref=ast_sto_dp_puis",
      },
      {
        name: "UnRuled Spiral Notebook - 300 Pages",
        sub: "Bundle Pack of Unruled Notebook",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "Unruled",
        image: "/product/4-pack.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Unruled-Notebook-Page/dp/B07VY1J1WD/ref=ast_sto_dp_puis",
      },
      {
        name: "UnRuled Spiral Notebook - 400 Pages",
        sub: "Bundle Pack of Notebook UnRuled Spiral",
        specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "Big notebook",
        image: "/product/5-subjects.jpg",
        href: "https://www.amazon.in/Ambi-Spiral-Notebook-A4-400-Unruled/dp/B07VVX8C2F/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "upsc-answer",
    label: "UPSC Answer Writing",
    products: [
      {
        name: "UPSC Mains Answer Writing Notebook - 200 Pages",
        sub: "For Endless QCAB practice in designated Pattern",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "For Mains",
        image: "/product/always-right.jpg",
        href: "https://www.amazon.in/amblitz-Writing-Notebook-Pre-Printed-Practice/dp/B088X661QN/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 300 Pages",
        sub: "Practice Answer Writing Presantation in UPSC Pattern",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "For practice",
        image: "/product/upsc-main.jpg",
        href: "https://www.amazon.in/Amblitz-Blank-Practice-Answer-Sheet/dp/B07Z27ZKF6/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 200 Pages",
        sub: "Word Limit Adherence with limited Space for Answer",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For Mains",
        image: "/product/upsc-mains.jpg",
        href: "https://www.amazon.in/amblitz-Notebooks-Pre-Printed-Practice-Notebook/dp/B07WZ31YBQ/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Sheets - 225 Sheets/ 450Pages",
        sub: "Loose Sheets to Make your own QCAB",
        specs: ["225 Pages", "70 GSM", "Thick Paper", "Loose Sheets"],
        tag: "For practice",
        image: "/product/loose-sheet.jpg",
        href: "https://www.amazon.in/Amblitz-Answer-Writing-Practice-Sheets/dp/B09DR7PXQJ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 300 Pages",
        sub: "Helpful in USPC / PSC Exam Practice",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For Mains",
        image: "/product/upsc.webp",
        href: "https://www.amazon.in/amblitz-Notebook-Notebooks-PrePrinted-Services/dp/B07WZ5439K/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 400 Pages",
        sub: "For No stone Unturned - Practice Regime",
        specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For Mains",
        image: "/product/patience.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-PrePrinted-Services-Aspirant/dp/B07WZ4K27W/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 500 Pages",
        sub: "Practice Marathon Needs bulky Notebooks of 500 Pages",
        specs: ["500 Pages", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For Mains",
        image: "/product/optional.jpg",
        href: "https://www.amazon.in/amblitz-Writing-Notebook-Service-Printed/dp/B08M47B4TY/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 200 Pages",
        sub: "Bundle Packs of UPSC Answer writing Notebooks",
        specs: ["200 Pages", "70 GSM", "Thick Paper", "Pack of 5"],
        tag: "For Mains",
        image: "/product/upsc-5-set.jpg",
        href: "https://www.amazon.in/amblitz-Writing-Notebook-Service-Printed/dp/B07WZ3WWDR/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 300 Pages",
        sub: "Aesthetic Design with Message to Push",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 4"],
        tag: "For Mains",
        image: "/product/upsc-answer-writing.jpg",
        href: "https://www.amazon.in/amblitz-Writing-Notebook-PrePrinted-Services/dp/B07WZ3ZVWR/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 300 Pages",
        sub: "Bundle Packs of UPSC Answer writing Notebooks ",
        specs: ["300 Pages", "70 GSM", "Thick Paper", "Pack of 6"],
        tag: "For Mains",
        image: "/product/upsc.webp",
        href: "https://www.amazon.in/amblitz-Writing-Notebook-PrePrinted-Services/dp/B07Z261CS2/ref=ast_sto_dp_puis",
      },
      {
        name: "UPSC Mains Answer Writing Notebook - 400 Pages",
        sub: "Bundle Packs of UPSC Answer writing Notebooks",
        specs: ["400 Pages", "70 GSM", "Thick Paper", "Pack of 5"],
        tag: "For Prelims",
        image: "/product/upsc-prelims.jpg",
        href: "https://www.amazon.in/amblitz-Prelim-100MCQ-Practice-Answer/dp/B084LKXHJ3/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "UPSC Mains Answer Writing Notebook + OMR Sheets",
        sub: "Combo of 200 Pages Answer Writing Notebook and 50 OMR sheets of 100 MCQ Notebook",
        specs: ["Introductory Pack", "70 GSM", "Thick Paper", "Prelim + Mains Combo"],
        tag: "For Prelims",
        image: "/product/upsc-prelims.jpg",
        href: "https://www.amazon.in/amblitz-Prelim-100MCQ-Practice-Answer/dp/B084LKXHJ3/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "omr-practice",
    label: "OMR Sheets",
    products: [
      {
        name: "OMR Sheet for Practice - 180 MCQ - 100 Sheet Notebook",
        sub: "OMR Sheets to practice for D-Day",
        specs: ["180 MCQ", "70 GSM", "Thick Paper", "Pack of 1"],
        tag: "For mock tests",
        image: "/product/180-mcq.jpg",
        href: "https://www.amazon.in/Amblitz-Practice-Sheet-Spiral-Notebook/dp/B08LFJM1NS/ref=ast_sto_dp_puis",
      },
      {
        name: "OMR Sheet for Practice - 150 MCQ - 100 Sheet",
        sub: "Real Competitive Exam Feel",
        specs: ["150 MCQ", "70 GSM", "Thick Paper", "Loose Sheets"],
        tag: "For mock tests",
        image: "/product/150-mcq.jpg",
        href: "https://www.amazon.in/Amblitz-Sheet-Sheets-Practice-Answer/dp/B0BN8QSMHV/ref=ast_sto_dp_puis",
      },
      {
        name: "OMR Sheet for Practice - 100 MCQ - 100 Sheet",
        sub: "Helps in Ascertainng Time to Circle Buble",
        specs: ["100 MCQ", "70 GSM", "Thick Paper", "Loose Sheets"],
        tag: "For mock tests",
        image: "/product/100-mcq-loose.jpg",
        href: "https://www.amazon.in/Amblitz-OMR-Sheet-MCQs-Sheets/dp/B09HXY2DQV/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "OMR Sheet for Practice - 100 MCQ + 80 MCQ - 50 Sheets Each",
        sub: "GS1 and GS2 - Practice for Prelim in one Go",
        specs: ["100 MCQ + 80 MCQ", "70 GSM", "Thick Paper", "Prelims Combo"],
        tag: "For UPSC aspirants",
        image: "/product/100-80-omr.jpg",
        href: "https://www.amazon.in/amblitz-Prelim-Separate-Sheets-Aspirants/dp/B0DXFLQS48/ref=ast_sto_dp_puis",
      },
      {
        name: "OMR Sheet for Practice - 200 MCQ - 50 Sheet Notebook",
        sub: "Practice Avoids Wrong Circling",
        specs: ["200 MCQ", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For mock tests",
        image: "/product/neet-200.jpg",
        href: "https://www.amazon.in/Amblitz-Sheet-MCQs-Spiral-Notebook/dp/B08F2WNSX5/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "OMR Sheet for Practice - 180 MCQ - 50 Sheet Notebook",
        sub: "Set the Clock Start the Sheet to Manage the 180 Minutes",
        specs: ["180 MCQ", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "New pattern",
        image: "/product/neet-180.jpg",
        href: "https://www.amazon.in/amblitz-PATTERN-Sheets-Notebook-Spiral/dp/B082RGXZ3L/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "OMR Sheet for Practice - 100 MCQ - 50 Sheet Notebook",
        sub: "Every second Counts when you are competing Against Odds",
        specs: ["100 MCQ", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For mock tests",
        image: "/product/100-mcq.jpg",
        href: "https://www.amazon.in/Amblitz-Sheet-MCQs-Spiral-Notebook/dp/B07ZN77614/ref=ast_sto_dp_puis",
      },
      {
        name: "OMR Sheet for Practice - 100 MCQ - 100 Sheet Notebook",
        sub: "Total 200 Sheets for Rigorous Practice",
        specs: ["100 MCQ", "70 GSM", "Thick Paper", "Pack of 2"],
        tag: "For mock tests",
        image: "/product/100-mcq-2-notebook.jpg",
        href: "https://www.amazon.in/Amblitz-OMR-Sheet-Notebook-Pack/dp/B07ZQQXJ9G/ref=ast_sto_dp_puis",
      },
      {
        name: "OMR Sheet for Practice - 60 MCQ - 100 Sheet",
        sub: "60MCQ for CBSE Objective Exams",
        specs: ["60 MCQ", "70 GSM", "Thick Paper", "Loose Sheets"],
        tag: "For mock tests",
        image: "/product/cnse-board.jpg",
        href: "https://www.amazon.in/Amblitz-Sheet-Sheets-Questions-Practice/dp/B09LD65LPX/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "naam-pustika",
    label: "Nam Lekhan Pustika",
    products: [
      {
        name: "Naam Lekhan Pustika - 51,000 Naam - B5 Size",
        sub: "Classic Naam Lekhan in Modern Style 108 Boxes 3 Section per page",
        specs: ["51,000 Jaap", "108 Boxes Section", "Pack of 1"],
        tag: "4.7★ on Amazon",
        image: "/product/51000nam.jpg",
        href: "https://www.amazon.in/Amblitz-51000-Naam-Lekhan-Pustika/dp/B08D3T4DCB/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 22,000 Naam - B5 Size",
        sub: "Starter Pack to start writing Ram Nam Habit",
        specs: ["22,000 Naam", "108 Boxes Section", "Pack of 3"],
        tag: "Good for gifting",
        image: "/product/naam-22000.jpg",
        href: "https://www.amazon.in/amblitz-Pustika-Beginners-Notebooks-Organised/dp/B0CLVNJM2Y/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Naam Lekhan Pustika - 1,00,000 Naam - B5 Size",
        sub: "Comprehensive Ram Nam Lekhan Pustika with Broad Boxes",
        specs: ["1,00,000 Naam", "108 Boxes Section", "Pack of 1"],
        tag: "One lakh naam",
        image: "/product/nam-100000.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Organised-Spiral/dp/B0CLVQVN1V/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 51,000 Naam - B5 Size",
        sub: "Write Cum Recite Helps in Meditation",
        specs: ["51,000 Naam", "108 Boxes Section", "Pack of 2"],
        tag: "4.7★ on Amazon",
        image: "/product/naam-51000.jpg",
        href: "https://www.amazon.in/Amblitz-51000-Naam-Lekhan-Pustika/dp/B082Y6MRDV/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Naam Lekhan Pustika - 1,51,000 Naam - B5 Size",
        sub: "Gift for your Parents or person you Love and Care",
        specs: ["1,51,000 Jaap", "108 Boxes Section", "Pack of 1"],
        tag: "For meditation",
        image: "/product/151000naam.png",
        href: "https://www.amazon.in/amblitz-Pustika-Organised-Devoted-Meditation/dp/B0F9TQP65Y/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 2,00,000 Naam - B5 Size",
        sub: "Notebook for Pro who does not stop at One mala",
        specs: ["2,00,000 Jaap", "108 Boxes Section", "Pack of 1"],
        tag: "For meditation",
        image: "/product/200000naam.jpg",
        href: "https://www.amazon.in/amblitz-Pustika-Notebook-Devoted-Meditation/dp/B0HJM7R325/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 51,000 Naam - B5 Size",
        sub: "Bundle Pack of Ram Nam Lekhan Pustika",
        specs: ["51,000 Naam", "108 Boxes Section", "Pack of 5"],
        tag: "For gifting",
        image: "/product/naam-51000.jpg",
        href: "https://www.amazon.in/51000-Naam-Lekhan-Copy-Pack/dp/B082Y7C34V/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 21,000 Naam - Notepad Size",
        sub: "NotePad Style Notebook 108 Boxes in each Page",
        specs: ["21,000 Naam", "Notepad", "Pack of 4"],
        tag: "Travel friendly",
        image: "/product/21000naam.webp",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notepad-Friendly/dp/B0DZJ7L821/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 11,000 Naam - Pocket Size",
        sub: "Pocket Size Notebook easy to care",
        specs: ["11,000 Jaap", "Pocket Size", "Pack of 7"],
        tag: "Travel friendly",
        image: "/product/11000naam.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Pocket-Notepad/dp/B0DZJR1S9R/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Naam Lekhan Pustika - 11,000 Naam - Notepad Size",
        sub: "Travel Friendly Notebook - Purse or Bag Carry",
        specs: ["11,000 Naam", "Notepad", "Pack of 7"],
        tag: "Travel friendly",
        image: "/product/11000ramnaam.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notepad-Friendly/dp/B0DZJ5V347/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 5,100 Naam - Pocket Size",
        sub: "Daily travel in bus or Metro - Take out the Notebook from Pocket",
        specs: ["5,100 Jaap", "Pocket Size", "Pack of 15"],
        tag: "Travel friendly",
        image: "/product/51000ramnaamm.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Pocket-Notepad/dp/B0DZJQZWW2/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 21,000 Naam - Notepad Size",
        sub: "Instead of Screen Scrolling Write cum Recite Notebook",
        specs: ["21,000 Naam", "Notepad", "Pack of 8"],
        tag: "Travel friendly",
        image: "/product/21000ramnam.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notepad-Friendly/dp/B0DZJMBHFR/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 11,000 Naam - Pocket Size",
        sub: "Pocket Size Notebook easy to care",
        specs: ["11,000 Jaap", "Pocket Size", "Pack of 15"],
        tag: "Travel friendly",
        image: "/product/11000nam.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Pocket-Notepad/dp/B0DZJLT311/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 11,000 Naam - Notepad Size",
        sub: "Travel Friendly Notebook - Purse or Bag Carry",
        specs: ["11,000 Naam", "Notepad", "Pack of 15"],
        tag: "Travel friendly",
        image: "/product/11000namlekhan.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notepad-Friendly/dp/B0DZJ4VQX8/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 11,000 Naam - Pocket Size",
        sub: "Instead of Screen Scrolling Write cum Recite Notebook",
        specs: ["11,000 Jaap", "Pocket Size", "Pack of 15"],
        tag: "Traveller pack",
        image: "/product/jaapnaam.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notebooks-TravellerPack/dp/B0DYQ2H2FP/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 5,100 Naam - Pocket Size",
        sub: "Distribution Pack Write yourself and Gift to Dear Ones",
        specs: ["5,100 Naam", "Pocket Size", "Pack of 31"],
        tag: "Travel friendly",
        image: "/product/31notebook.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Pocket-Notepad/dp/B0DZKFQD6H/ref=ast_sto_dp_puis",
      },
      {
        name: "Naam Lekhan Pustika - 21,000 Naam - Notepad Size",
        sub: "Distribution Pack Write yourself and Gift to Dear Ones",
        specs: ["21,000 Jaap", "Notepad", "Pack of 15"],
        tag: "Travel friendly",
        image: "/product/108jaap.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Notepad-Friendly/dp/B0DZK2CM1T/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Naam Lekhan Pustika - 5,100 Naam - Pocket Size",
        sub: "Mass Distrubution Pack of Ram Nam Lekhan Pustika",
        specs: ["5,100 Naam", "Pocket size", "Pack of 51"],
        tag: "Travel friendly",
        image: "/product/51notepad.jpg",
        href: "https://www.amazon.in/amblitz-Lekhan-Pustika-Pocket-Notepad/dp/B0DZK9F21S/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
    ],
  },
  {
    id: "subject-spiral",
    label: "Subject Spiral",
    products: [
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 200 pages",
        sub: "Ruled - Subject Notebooks - Sections Separated with 5 Colored Index",
          specs: ["200 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/template.png",
        href: "https://www.amazon.in/Amblitz-Subject-Spiral-Notebook-200Pages/dp/B08PPFYY2D/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 200 pages",
        sub: "Unruled - Spiral Notebook - Sections for Semester - Subject - Topic - Lecture",
        specs: ["200 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/5-subjects.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7KFHWK/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 250 pages",
        sub: "Ruled - Subject Notebooks - College Notebook",
        specs: ["250 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/notebook-omr.jpg",
        href: "https://www.amazon.in/Amblitz-Subject-Spiral-Notebook-250Pages/dp/B08PPMKCDZ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 250 pages",
        sub: "Unruled - Spiral Notebook - Color Index - Easier to Segregate",
        specs: ["250 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/unruled-500-pages.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7L6M75/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 6 Subject - 300 pages",
        sub: "Ruled - Subject Notebooks - Durable Flexible Notebooks for Note Taking",
        specs: ["300 Pages", "Ruled - 70 GSM", "6 Subject"],
        tag: "For multi-subject notes",
        image: "/product/always-right.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-Subjects-300Pages/dp/B08PKXSL84/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - 6 Subject - 300 pages",
        sub: "Unruled - Spiral Notebook - Spirals for College Students",
        specs: ["300 Pages", "UnRuled - 70 GSM", "6 Subject"],
        tag: "For multi-subject notes",
        image: "/product/notebook-omr.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08PKV2MN5/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 300 pages",
        sub: "Ruled - Subject Notebooks - Sections Separated with 5 Colored Index",
        specs: ["300 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/unruled-500-pages.jpg",
        href: "https://www.amazon.in/Amblitz-Subject-Spiral-Notebook-300Pages/dp/B085297VH1/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 300 pages",
        sub: "Unruled - Spiral Notebook - Single Notebook for Different Purpose",
        specs: ["300 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/unruled.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7KK2PP/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 400 pages",
        sub: "Ruled - Subject Notebooks - Multiple Section Multi Purpose",
        specs: ["400 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/5-subject-400.jpg",
        href: "https://www.amazon.in/Amblitz-Subject-Spiral-Notebook-400Pages/dp/B0852B74TJ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 400 pages",
        sub: "Ruled - Subject Notebooks - Sections Separated with 5 Colored Index",
        specs: ["400 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7KXH5S/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 500 pages",
        sub: "Unruled - Spiral Notebook - Sections for Semester - Subject - Topic - Lecture",
        specs: ["500 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/5-subjects.jpg",
        href: "https://www.amazon.in/Amblitz-Subject-Spiral-Notebook-500Pages/dp/B08529TG2F/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 500 pages",
        sub: "Ruled - Subject Notebooks - College Notebook",
        specs: ["500 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/2-choice.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7JFS9D/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 5 Subject - 600 pages",
        sub: "Unruled - Spiral Notebook - Color Index - Easier to Segregate",
        specs: ["600 Pages", "Ruled - 70 GSM", "5 Subject"],
        tag: "Biggest notebook",
        image: "/product/notebook-omr.jpg",
        href: "https://www.amazon.in/Amblitz-Subject-Mega-Spiral-Notebook/dp/B08PPMRR5N/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - 6 Subject - 600 pages",
        sub: "Ruled - Subject Notebooks - Durable Flexible Notebooks for Note Taking",
        specs: ["600 Pages", "UnRuled - 70 GSM", "6 Subject"],
        tag: "For multi-subject notes",
        image: "/product/always-right.jpg",
        href: "https://www.amazon.in/Amblitz-Unruled-Spiral-Notebook-Subjects/dp/B08PL3N98H/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - 6 Subject - 600 pages",
        sub: "Unruled - Spiral Notebook - Spirals for College Students",
        specs: ["600 Pages", "Ruled - 70 GSM", "6 Subject"],
        tag: "Biggest notebook",
        image: "/product/push-yourself.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-Subjects-600Pages/dp/B08PKZJFHS/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - 5 Subject - 600 pages",
        sub: "Ruled - Subject Notebooks - Sections Separated with 5 Colored Index",
        specs: ["600 Pages", "UnRuled - 70 GSM", "5 Subject"],
        tag: "For multi-subject notes",
        image: "/product/unruled-500-pages.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-UnRuled-Subjects/dp/B08T7KCM6Y/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "specialized-format",
    label: "Specialized Format",
    products: [
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["200 Pages", "Specialized Format", "Pack of 1"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DPZWR9/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["300 Pages", "Specialized Format", "Pack of 1"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DQL2QJ/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["400 Pages", "Specialized Format", "Pack of 1"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DRD7YF/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["200 Pages", "Specialized Format", "Pack of 2"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DR9Q2H/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["400 Pages", "Specialized Format", "Pack of 2"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DSL7HV/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["200 Pages", "Specialized Format", "Pack of 4"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DR4ZXB/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Speialized Format - 3 part Notebook",
        sub: "Specialized 3 Part Format for Current Affairs, Case Study, General Study",
        specs: ["300 Pages", "Specialized Format", "Pack of 3"],
        tag: "For notemaking",
        image: "/product/template.png",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Template-Notemaking/dp/B0C5DNZQX4/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "rough-notebook",
    label: "Rough Notebook",
    products: [
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["600 Pages", "Cheap", "Pack of 1"],
        tag: "Budget pick",
        image: "/product/rough-1.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Spiral-Notebook-Single/dp/B08FCLZS1C/ref=ast_sto_dp_puis",
      },
      {
        name: "Rough Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["212 Pages", "Cheap", "Pack of 3"],
        tag: "Budget pick",
        image: "/product/rough-2.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Notebook-Page-Single/dp/B08FYND2YF/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Rough Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["140 Pages", "Cheap", "Pack of 5"],
        tag: "Budget pick",
        image: "/product/rough-3.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Notebook-Page-Single/dp/B08FTHBLS5/ref=ast_sto_dp_puis",
      },
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["400 Pages", "Cheap", "Pack of 2"],
        tag: "Budget pick",
        image: "/product/rough-4.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Spiral-Notebook-Single/dp/B08FCMNYGM/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Rough Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["300 Pages", "Cheap", "Pack of 4"],
        tag: "Budget pick",
        image: "/product/rough-1.jpg",
        href: "https://www.amazon.in/Rough-Ambi-Notebook-Soft-Cover/dp/B07WSG2BZZ/ref=ast_sto_dp_puis",
      },
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["500 Pages", "Cheap", "Pack of 3"],
        tag: "Big notebook",
        image: "/product/rough-2.jpg",
        href: "https://www.amazon.in/Amblitz-Spiral-Notebook-A4-500-Single/dp/B07VZ4Y116/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["1000 Pages", "Cheap", "Pack of 2"],
        tag: "Budget pick",
        image: "/product/rough-3.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Spiral-Notebook-Notebooks/dp/B09BZMHCB5/ref=ast_sto_dp_puis",
      },
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["500 Pages", "Cheap", "Pack of 4"],
        tag: "Budget pick",
        image: "/product/rough-4.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-Notebooks-Student-Practice/dp/B07VX31319/ref=ast_sto_dp_puis",
      },
      {
        name: "Rough Spiral Notebook - Cheap Notebooks for Single Use",
        sub: "Black Thin Paper for single time usage. Cheap Notebooks for Practice",
        specs: ["600 Pages", "Cheap", "Pack of 5"],
        tag: "Budget pick",
        image: "/product/rough-1.jpg",
        href: "https://www.amazon.in/Amblitz-Rough-Spiral-Notebook-Single/dp/B08FCL1YPV/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "rainbow-series",
    label: "Rainbow Series",
    products: [
      {
        name: "Spiral Notebook - Ruled - Rainbow Series - 600 Pages",
        sub: "Different color Paper used for 6 sections in this Mega Notebook like Rainbow in the SKY",
        specs: ["600 Pages", "Rainbow Series", "70 GSM", "Thick Paper"],
        tag: "For multi-subject notes",
        image: "/product/moon.jpg",
        href: "https://www.amazon.in/Amblitz-Notebook-Subjects-Colour-Rainbow/dp/B08XM24B8Z/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - Rainbow Series - 1000 Pages",
        sub: "Different color Paper used for 6 sections in this Mega Notebook like Rainbow in the SKY",
        specs: ["1000 Pages", "Rainbow Series", "70 GSM", "Thick Paper"],
        tag: "For multi-subject notes",
        image: "/product/sunrise.jpg",
        href: "https://www.amazon.in/Amblitz-Notebook-Subjects-Colour-Rainbow/dp/B08XLRYSLS/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "spiral-b5",
    label: "Spiral · B5 Size",
    products: [
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 160 Pages",
        sub: "Compact Size Notebook for Notes Taking and easy to carry",
        specs: ["160 Pages", "UnRuled", "B5 Size"],
        tag: "Everyday notebook",
        image: "/product/b5-1.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-UNRULED-Studentss-Personal/dp/B0CNPY9FTZ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 200 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["200 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-2.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9MC8YD/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 300 Pages",
        sub: "Compact Size Notebook for Notes Taking and easy to carry",
        specs: ["300 Pages", "UnRuled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-3.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9M8YVD/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 300 Pages",
        sub: "Aesthetic Design with Quote",
        specs: ["300 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-1.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9LVL12/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 400 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["400 Pages", "UnRuled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-5.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9K896W/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 400 Pages",
        sub: "Compact Size Notebook for Notes Taking and easy to carry",
        specs: ["400 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-2.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9LKMD8/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 500 Pages",
        sub: "Aesthetic Design with Quote",
        specs: ["500 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-7.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9KCHMW/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 500 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["500 Pages", "UnRuled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-8.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9JDGKV/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 300 Pages",
        sub: "Compact Size Notebook for Notes Taking and easy to carry",
        specs: ["300 Pages", "Unruled", "B5 Size"],
        tag: "Everyday notebook",
        image: "/product/b5-2.jpg",
        href: "https://www.amazon.in/amblitz-Unruled-Notebook-Studentss-Personal/dp/B0CMQSJG85/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 600 Pages",
        sub: "Aesthetic Design with Quote",
        specs: ["600 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-10.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9KRX73/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 600 Pages",
        sub: "Spirals with 70 GSM Thick Paper No-Bleed",
        specs: ["600 Pages", "UnRuled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-11.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9K8GCS/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Ruled - B5 Size - 1000 Pages",
        sub: "Mega Notebook for Rigorous Practice",
        specs: ["1000 Pages", "Ruled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-3.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9LMX7J/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - UnRuled - B5 Size - 1000 Pages",
        sub: "Mega Notebook for 'Not to Miss Anything Notes'",
        specs: ["1000 Pages", "UnRuled", "B5 Size"],
        tag: "For college",
        image: "/product/b5-1.jpg",
        href: "https://www.amazon.in/amblitz-Notebook-College-Studentss-Personal/dp/B0CM9NNT8X/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "school-copy",
    label: "Copy for School",
    products: [
      {
        name: "Soft Cover Notebook - Copy for the Kids - 144 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "144 Pages", "Pack of 5"],
        tag: "For school kids",
        image: "/product/copy-1.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Cover-Notebook-Single/dp/B07WZ6WGCD/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 184 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "184 Pages", "Pack of 4"],
        tag: "For school kids",
        image: "/product/copy-2.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Cover-Notebook-Single/dp/B07WZ4S4WG/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 96 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "96 Pages", "Pack of 6"],
        tag: "For school kids",
        image: "/product/copy-3.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Cover-Notebook-Single/dp/B08JM5LMHN/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 96 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "96 Pages", "Pack of 6"],
        tag: "For school kids",
        image: "/product/copy-4.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Notebook-Combo-Single-English/dp/B08JM465VV/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 120 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "120 Pages", "Pack of 6"],
        tag: "For school kids",
        image: "/product/copy-1.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Notebook-Combo-All-Subject/dp/B07WZ6GYY2/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 120 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "120 Pages", "Pack of 6"],
        tag: "For school kids",
        image: "/product/copy-2.jpg",
        href: "https://www.amazon.in/Amblitz-Copy-Notebook-Combo-Single-English/dp/B088M1WF5J/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 120 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "120 Pages", "Pack of 6"],
        tag: "For school kids",
        image: "/product/copy-3.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Cover-Notebook-Single/dp/B07WYRJ6QM/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Copy for the Kids - 120 Pages",
        sub: "Copy for School Kids Elementary Level Notebook Smooth Paper for Pencil Use",
        specs: ["Copy", "120 Pages", "Pack of 12"],
        tag: "For school kids",
        image: "/product/copy-4.jpg",
        href: "https://www.amazon.in/Ambi-Copy-Cover-Notebook-Single/dp/B07WZ6KWF8/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "soft-cover",
    label: "Soft Cover Notebook",
    products: [
      {
        name: "Soft Cover Notebook - Ruled - 104 Pages - A4 Size",
        sub: "Classic Notebook for the student note taking and practice",
        specs: ["A4 Size", "104 Pages", "Pack of 4"],
        tag: "Everyday notebook",
        image: "/product/softcover-1.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-Single/dp/B07WZ4R9TW/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Ruled - 144 Pages - Regular Size",
        sub: "Classic Notebook for the School Student for school and Tuition",
        specs: ["17 X 27 CM", "144 Pages", "Pack of 4"],
        tag: "Compact size",
        image: "/product/softcover-2.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-17/dp/B07WZ63KWW/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Ruled - 96 Pages - Regular Size",
        sub: "Notebook for School , Tuition - Practice, Note Taking",
        specs: ["17 X 27 CM", "96 Pages", "Pack of 6"],
        tag: "Compact size",
        image: "/product/softcover-3.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-17/dp/B07WZ55581/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Ruled - 120 Pages - Regular Size",
        sub: "Classic Notebook for the student note taking and practice",
        specs: ["17 X 27 CM", "120 Pages", "Pack of 5"],
        tag: "Compact size",
        image: "/product/softcover-2.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-17/dp/B07WZ1HRS3/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Ruled - 184 Pages - Regular Size",
        sub: "Classic Notebook for the School Student for school and Tuition",
        specs: ["17 X 27 CM", "184 Pages", "Pack of 4"],
        tag: "School register",
        image: "/product/softcover-2.jpg",
        href: "https://www.amazon.in/Amblitz-Regular-Register-Notebook-Single/dp/B08KGXTN3Q/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - UnRuled - 224 Pages - A4 Size",
        sub: "Notebook for School , Tuition - Practice, Note Taking",
        specs: ["A4 Size", "224 Pages", "Pack of 4"],
        tag: "Unruled",
        image: "/product/softcover-1.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-Unruled/dp/B07XFNDTCQ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Ruled - 184 Pages - A4 Size",
        sub: "Classic Notebook for the student note taking and practice",
        specs: ["A4 Size", "184 Pages", "Pack of 5"],
        tag: "Everyday notebook",
        image: "/product/softcover-7.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-Single/dp/B07WZ2YXHC/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Soft Cover Notebook - Ruled - 232 Pages - Regular Size",
        sub: "Classic Notebook for the School Student for school and Tuition",
        specs: ["17 X 27 CM", "232 Pages", "Pack of 6"],
        tag: "Compact size",
        image: "/product/softcover-3.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-17/dp/B07WZ4WYG8/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Ruled - 160 Pages - A4 Size",
        sub: "Notebook for School , Tuition - Practice, Note Taking",
        specs: ["A4 Size", "160 Pages", "Pack of 6"],
        tag: "Everyday notebook",
        image: "/product/softcover-7.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-Single/dp/B07WYRH2R6/ref=ast_sto_dp_puis",
      },
      {
        name: "Soft Cover Notebook - Ruled - 200 Pages - A4 Size",
        sub: "Classic Notebook for the School Student for school and Tuition",
        specs: ["A4 Size", "200 Pages", "Pack of 5"],
        tag: "Everyday notebook",
        image: "/product/softcover-1.jpg",
        href: "https://www.amazon.in/Ambi-Soft-Cover-Notebook-Single/dp/B07WZ67W2P/ref=ast_sto_dp_puis",
      },
    ],
  },
  {
    id: "spiral-a5",
    label: "Spiral · A5 Size",
    products: [
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-1.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N8KNK7/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-2.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N8J7JQ/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-3.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N8D8M8/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-4.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N81WST/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-5.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N7SL5M/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-6.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N7QW8F/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-7.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N7P33C/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-8.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N7KXC7/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-9.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N77WRD/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-10.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085N6XQ36/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - 5 Different Color Pages - 200 Pages",
        sub: "5 Different Color Pages Notebook with Aesthic Covers",
        specs: ["Ruled", "A5 Size", "Pack of 2"],
        tag: "Compact size",
        image: "/product/a5-11.jpg",
        href: "https://www.amazon.in/Amblitz-A5-Spiral-Notebook-Pages/dp/B085MHTHW3/ref=ast_sto_dp_puis",
      },
      {
        name: "Spiral Notebook - Unruled - 200 Pages",
        sub: "Unruled Small Notebook with 70 GSM Thick Smooth Paper",
        specs: ["Unruled", "A5 Size", "Pack of 2"],
        tag: "Unruled",
        image: "/product/a5-12.jpg",
        href: "https://www.amazon.in/Ambi-A5-Spiral-Notebook-Unruled/dp/B07X9NDHKJ/ref=ast_sto_dp_puis_mod_primary_new?sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D",
      },
    ],
  },
  {
    id: "drawing-file",
    label: "Drawing File",
    products: [
      {
        name: "Drawing Notebook for Kids - 32 Pages / 16 Sheets",
        sub: "Pencil , Dry Crayons , Sketching and Drawing Notebook Not for Oil or Water Color",
        specs: ["32 Pages", "100 GSM", "Pack of 6"],
        tag: "For students",
        image: "/product/drawing-1.jpg",
        href: "https://www.amazon.in/Amblitz-Students-Sketching-Colouring-Painting/dp/B0BXF7MFDG/ref=ast_sto_dp_puis",
      },
      {
        name: "Drawing Notebook for Kids - 32 Pages / 16 Sheets",
        sub: "Pencil , Dry Crayons , Sketching and Drawing Notebook Not for Oil or Water Color",
        specs: ["32 Pages", "100 GSM", "Pack of 3"],
        tag: "For students",
        image: "/product/drawing-2.jpg",
        href: "https://www.amazon.in/Drawing-Pad-Students-Sketching-Colouring/dp/B0BN8SB7JJ/ref=ast_sto_dp_puis",
      },
    ],
  },
];

export const faqs = [
  {
    q: "Will these OMR sheets match my actual exam paper?",
    a: "They are specimens, not reprints. The bubble size, spacing and answer-key layout follow the standard offline pattern so your hand learns the rhythm — but every board designs its own sheet, so read the instructions printed on your real paper on exam day.",
  },
  {
    q: "Which pen should I use to fill the bubbles?",
    a: "Blue or black ballpoint only. These sheets are read by an optical scanner, so gel ink that bleeds through or a pencil that smudges is exactly what you want to discover at home, not in the hall.",
  },
  {
    q: "What paper do you print on?",
    a: "70 GSM thick white paper across the range. It takes ballpoint without ghosting on the reverse, and it is heavy enough that a spiral notebook survives being shoved into a bag every day for a year.",
  },
  {
    q: "How many naam fit in one Lekhan Pustika?",
    a: "It depends on the book. The beginner pack holds 22,000, the popular one holds 51,840 in sections of 108 boxes, and the largest runs to 1,51,000 across 468 pages. Each box is a broad 18 × 6 mm, sized so an elderly hand can write Ram Ram comfortably.",
  },
  {
    q: "Can I write a name other than Ram in the pustika?",
    a: "Yes. The boxes are blank and the cover deliberately carries no deity image, so the same book works for Om Sai Ram, Om Namah Shivay, Jai Shri Shyam, Jai Mata Di or any naam you follow. It also makes the finished book simple to keep or offer respectfully.",
  },
  {
    q: "Do you take bulk orders for coaching centres or satsang groups?",
    a: "Yes. Institutional quantities of OMR sheets, answer booklets and pustikas ship direct. Write in with the quantity and the format you need and you get a quote back with delivery timelines.",
  },
  {
    q: "Where do I buy, and how fast does it reach me?",
    a: "Everything is listed on the amBlitz Amazon store and fulfilled by Amazon, so delivery follows your usual Prime timeline. Larger institutional orders are dispatched separately.",
  },
];

export const stats = [
  { value: "70", unit: "GSM", label: "paper across every product" },
  { value: "1,51,000", unit: "", label: "naam in the largest pustika" },
  { value: "108", unit: "boxes", label: "per section, the traditional count" },
  { value: "4.7", unit: "★", label: "on the 51,000 pustika, 163 ratings" },
];

export const testimonials = [
  {
    quote:
      "I timed my first mock on these and lost eleven minutes just circling. Now that number is under six. Nothing else in my prep gave me that back so quickly.",
    who: "Aarushi M.",
    role: "NEET repeater, Kota",
    tone: "leaf",
  },
  {
    quote:
      "The printed margin is the whole point. You stop writing an essay and start writing an answer, because the space tells you when to stop.",
    who: "Devansh R.",
    role: "UPSC Mains aspirant, Delhi",
    tone: "mango",
  },
  {
    quote:
      "Maa is seventy-four. The boxes are broad enough that she writes a full section without her glasses slipping down. She has finished four books.",
    who: "Sunita Agarwal",
    role: "Bought the 51,000 pustika",
    tone: "marigold",
  },
  {
    quote:
      "We run 400 students through a Sunday mock. Loose sheets, correct bubble pitch, no jamming in the scanner. That is all I need from a supplier.",
    who: "Rajesh Nair",
    role: "Coaching centre owner, Kochi",
    tone: "ink",
  },
];

export const buyingChannels = [
  {
    name: "Amazon store",
    line: "The full range, fulfilled by Amazon on your usual delivery timeline.",
    cta: "Open the store",
    href: STORE_URL,
  },
  {
    name: "Bulk & institutional",
    line: "Coaching centres, schools, temples and satsang groups — direct dispatch with a quote.",
    cta: "Ask for a quote",
    href: "#bulk",
  },
  {
    name: "Other marketplaces",
    line: "Selected titles are also listed on JioMart and other Indian marketplaces.",
    cta: "See what's listed",
    href: STORE_URL,
  },
];
